### PR TITLE
Package with csproj and build as AnyCPU

### PR DESCRIPTION
**Pull request by natemcmaster**
Remove makefile.shade and packages with csproj only
Build default .NET Framework assembly as AnyCPU instead of x64
Removes the dummy csproj for x86

### CODE REVIEW

**Comment by pranavkm** [comment]
I was hoping we could remove a lot of this when we do https://github.com/aspnet/Coherence-Signed/issues/401. Let me consult with the powers to be and see if we can make that change here instead.

**Comment by natemcmaster** [comment]
The package can target .NET Standard, but won't it still need to compile for .NET Framework and .NET Core?

**Comment by natemcmaster** [comment]
:bell:. Can we take care of the ".NET Framework or not" question in a separate PR? This one is just about removing the dependency on Sake to pack.

**Comment by pranavkm** [comment]
I'd rather not make all these changes to the build if we can avoid it. If you'd like you could move the Sake reference to this project's `repo.props` once https://github.com/aspnet/KoreBuild/issues/177 is addressed.

**Comment by natemcmaster** [comment]
Can you explain why you want to stick with Sake? I won't make a PR to add Sake to this repo. We are actively working towards removing it completely from our build system.

**Comment by pranavkm** [comment]
#90 should supersede this.

**Pull request closed without merging**
