### PR TITLE
Fix Downgrade Warnings

### PR DESCRIPTION
**Pull request by mikaelm12**
@ryanbrandenburg @natemcmaster  @muratg @kichalla

### CODE REVIEW

**Comment by kichalla** [comment]
- Can we see this change's effect in travis & appveyor?
- Have you tried this too? ;-) https://github.com/aspnet/universe#verifying-cross-repo-changes

**Comment by natemcmaster** [comment]
> Can we see this change's effect in travis & appveyor?

Add this to the branches list
```yml
- /^rel\/.*/
```

**Comment by mikaelm12** [comment]
@kichalla 

> Have you tried this too? ;-) https://github.com/aspnet/universe#verifying-cross-repo-changes
Yeah, Warnings all gone 😄

**Comment by kichalla** [comment]
Thanks! @mikaelm12 ...could you please enable the builds on travis & appveyor too?

**Comment by kichalla** [comment]
@mikaelm12 : quick question, did you hit any issues when building (just Compilation) Universe?

**Comment by mikaelm12** [comment]
@muratg We still want this for preview 2 right?

**Pull request merged**
